# Generated by Django 4.1.2 on 2022-11-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('año', models.PositiveIntegerField(default=0)),
                ('color', models.DateTimeField(auto_now_add=True)),
                ('tipo_combustible', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('puertas', models.PositiveIntegerField(default=0)),
                ('transmision', models.CharField(max_length=200)),
                ('motor', models.PositiveIntegerField(default=0)),
                ('tipo_carroceria', models.CharField(max_length=200)),
            ],
        ),
    ]
